# Generated by Django 4.1.3 on 2022-11-26 01:40

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("charity_finder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("org_id", models.IntegerField()),
                ("mission", models.TextField()),
                ("activeProjects", models.IntegerField()),
                ("totalProjects", models.IntegerField()),
                ("ein", models.CharField(max_length=200)),
                ("logoUrl", models.CharField(max_length=200)),
                ("addressLine1", models.CharField(max_length=200)),
                ("addressLine2", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("postal", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                (
                    "country_home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="charity_finder.country",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="charity_finder.theme",
                    ),
                ),
            ],
        ),
    ]
