# Generated by Django 4.1.3 on 2022-11-27 08:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("charity_finder", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("org_id", models.IntegerField(blank=True, default=0, null=True)),
                ("mission", models.TextField(blank=True, default="", null=True)),
                (
                    "activeProjects",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "totalProjects",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("ein", models.CharField(blank=True, max_length=200, null=True)),
                ("logoUrl", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "addressLine1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "addressLine2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("postal", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "country_home",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("themes", models.JSONField(blank=True, default=dict, null=True)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("countries", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
