# Generated by Django 4.1.3 on 2022-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity_finder", "0002_country_org"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
        migrations.RemoveField(
            model_name="org",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="org",
            name="themes",
        ),
        migrations.AddField(
            model_name="org",
            name="countries",
            field=models.ManyToManyField(
                related_name="countries", to="charity_finder.country"
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="themes",
            field=models.ManyToManyField(
                related_name="themes", to="charity_finder.theme"
            ),
        ),
    ]
