# Generated by Django 4.1.3 on 2022-11-27 07:51

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("charity_finder", "0002_country_org"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="org",
            name="theme",
        ),
        migrations.AddField(
            model_name="org",
            name="countries",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="org",
            name="themes",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="country",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="org",
            name="activeProjects",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="org",
            name="country_home",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="org",
            name="mission",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="org",
            name="org_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="org",
            name="totalProjects",
            field=models.IntegerField(default=0),
        ),
    ]
