# Generated by Django 4.1.3 on 2022-12-11 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charity_finder", "0003_region_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="country_home",
        ),
        migrations.RemoveField(
            model_name="project",
            name="country_home_code",
        ),
        migrations.RemoveField(
            model_name="project",
            name="theme_name",
        ),
        migrations.AddField(
            model_name="project",
            name="primary_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="charity_finder.country",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="primary_theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="charity_finder.theme",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="goal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="goal_remaining",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="long_term_impact",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="need",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="progress_report_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="project",
            name="region",
        ),
        migrations.AlterField(
            model_name="project",
            name="videos",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="charity_finder.region",
            ),
        ),
    ]
