# Generated by Django 4.1.3 on 2022-12-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity_finder", "0004_remove_project_country_home_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="active",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
