# Generated by Django 4.1.3 on 2022-12-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity_finder", "0006_alter_project_funding_alter_project_goal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="charity_finder.country"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="charity_finder.theme"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="charity_finder.theme"
            ),
        ),
    ]
