# Generated by Django 4.1.7 on 2023-03-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charity_finder", "0007_alter_organization_countries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="charity_finder.country"
            ),
        ),
    ]
